/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmyshow;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class event extends javax.swing.JFrame {

    /**
     * Creates new form event
     */
    public event() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        platinum = new javax.swing.JRadioButton();
        gold = new javax.swing.JRadioButton();
        silver = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nseat = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EVENT NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 78, -1, -1));
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 75, 90, -1));

        platinum.setBackground(new java.awt.Color(204, 204, 204));
        platinum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        platinum.setForeground(new java.awt.Color(255, 255, 255));
        platinum.setText("PLATINUM");
        platinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platinumActionPerformed(evt);
            }
        });
        getContentPane().add(platinum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        gold.setBackground(new java.awt.Color(204, 204, 204));
        gold.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gold.setForeground(new java.awt.Color(255, 255, 255));
        gold.setText("GOLD");
        gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldActionPerformed(evt);
            }
        });
        getContentPane().add(gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        silver.setBackground(new java.awt.Color(204, 204, 204));
        silver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        silver.setForeground(new java.awt.Color(255, 255, 255));
        silver.setText("SILVER");
        silver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silverActionPerformed(evt);
            }
        });
        getContentPane().add(silver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NO OF SEATS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 179, -1, -1));
        getContentPane().add(nseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 176, 60, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 0, -1, -1));

        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 259, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/GPAA_THEATRE95_LIVRAISON_HD-26 - Copy (2).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new usermain().setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new entry().setVisible(true);
        
    }//GEN-LAST:event_logoutActionPerformed

    private void platinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platinumActionPerformed
        // TODO add your handling code here:
        String a="plat";
        status.type=a;
    }//GEN-LAST:event_platinumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            connection cn=new connection();
            ResultSet rs1;
            cn.connect();
            int t,flag=0;
            String str1=ename.getText();
            String str2=nseat.getText();
            String q1="select * from eventseat where ename='"+str1+"'";
            String q2="select * from eventcost where ename='"+str1+"'";
            int s=Integer.parseInt(str2);
            
            cn.rs=cn.st.executeQuery(q1);
            
            
            
                
            while(cn.rs.next())
            {
               // System.out.println("hello");
                if(status.type.equals("plat"))
                {
                    t=cn.rs.getInt(2);
                    if(s<t)
                    {
                        flag=1;
                        t=t-s;
                        String que="Update eventseat set pt='"+t+"' where ename='"+str1+"'";
                        cn.st.executeUpdate(que);
                        rs1=cn.st.executeQuery(q2);
                        
                        t=t*s;
                        String st=String.valueOf(t);
                        jLabel3.setText("pay "+st);
                        
                        
                        
                        JOptionPane.showMessageDialog(null,"Booked Successfully");
                    }
                }
                else if(status.type.equals("gold"))
                {
                    t=cn.rs.getInt(3);
                     if(s<t)
                    {
                        flag=1;
                        t=t-s;
                        String que="Update eventseat set gd='"+t+"' where ename='"+str1+"'";
                        cn.st.executeUpdate(que);
                        rs1=cn.st.executeQuery(q2);
                        
                        t=t*s;
                        String st=String.valueOf(t);
                        jLabel3.setText("pay "+st);
                        
                        JOptionPane.showMessageDialog(null,"Booked Successfully");
                    }
                    
                }
                else
                {
                    t=cn.rs.getInt(4);
                     if(s<t)
                    {
                        flag=1;
                        t=t-s;
                        String que="Update eventseat set pt='"+t+"' where ename='"+str1+"'";
                        cn.st.executeUpdate(que);
                        rs1=cn.st.executeQuery(q2);
                        
                        t=t*s;
                         String st=String.valueOf(t);
                        jLabel3.setText("PAY "+st);
                        JOptionPane.showMessageDialog(null,"Booked Successfully");
                    }
                }
               
                if(flag==0)
                    JOptionPane.showMessageDialog(null,"No Tickets Available");
                
            
            }
            
             
        } catch (SQLException ex) {
            Logger.getLogger(event.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(event.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void goldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldActionPerformed
        // TODO add your handling code here:
        String a="gold";
        status.type=a;
    }//GEN-LAST:event_goldActionPerformed

    private void silverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silverActionPerformed
        // TODO add your handling code here:
        String a="silver";
        status.type=a;
    }//GEN-LAST:event_silverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField ename;
    private javax.swing.JRadioButton gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nseat;
    private javax.swing.JRadioButton platinum;
    private javax.swing.JRadioButton silver;
    // End of variables declaration//GEN-END:variables
}
