/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sports.java
 *
 * Created on Jan 17, 2017, 1:01:15 AM
 */

package bookmyshow;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author students
 */
public class sports extends javax.swing.JFrame {

    /** Creates new form sports */
    public sports() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        eventcode = new javax.swing.JTextField();
        platinum = new javax.swing.JRadioButton();
        gold = new javax.swing.JRadioButton();
        silver = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        seatno = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        book = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("EVENT CODE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        eventcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventcodeActionPerformed(evt);
            }
        });
        getContentPane().add(eventcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, -1));

        platinum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        platinum.setText("PLATINUM");
        platinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platinumActionPerformed(evt);
            }
        });
        getContentPane().add(platinum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        gold.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gold.setText("GOLD");
        getContentPane().add(gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        silver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        silver.setText("SILVER");
        getContentPane().add(silver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NO OF SEATS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        getContentPane().add(seatno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 35, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        book.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/6.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventcodeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new usermain().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new entry().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        try {
            // TODO add your handling code here:
            connection c=new connection();
            c.connect();
            String q="select * from eventseat";
            String e1=eventcode.getText();
            int e=Integer.parseInt(e1);
            String p1=platinum.getText();
            int p=Integer.parseInt(p1);
            String gd=gold.getText();
            int g=Integer.parseInt(gd);
            String sl=silver.getText();
            int s=Integer.parseInt(sl);
            String n1=seatno.getText();
            int n=Integer.parseInt(n1);
            try {
                c.rs=c.st.executeQuery(q);
            } catch (SQLException ex) {
                Logger.getLogger(sports.class.getName()).log(Level.SEVERE, null, ex);
            }
            int ec,pla,gol,sil;
            while(c.rs.next())
            {
                ec=c.rs.getInt(1);
            
                
                
                    
                    }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(sports.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_bookActionPerformed

    private void platinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platinumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_platinumActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton back;
    javax.swing.JButton book;
    javax.swing.JTextField eventcode;
    javax.swing.JRadioButton gold;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel8;
    javax.swing.JButton logout;
    javax.swing.JRadioButton platinum;
    javax.swing.JTextField seatno;
    javax.swing.JRadioButton silver;
    // End of variables declaration//GEN-END:variables

}
