/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * usermain.java
 *
 * Created on Jan 17, 2017, 12:27:17 AM
 */

package bookmyshow;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author students
 */
public class usermain extends javax.swing.JFrame {

    /** Creates new form usermain */
    public usermain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinema = new javax.swing.JButton();
        event = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cinema.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cinema.setText("CINEMA");
        cinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemaActionPerformed(evt);
            }
        });
        getContentPane().add(cinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        event.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        event.setText("EVENT");
        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });
        getContentPane().add(event, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new fcinema().setVisible(true);
        
        

    }//GEN-LAST:event_cinemaActionPerformed

    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new event().setVisible(true);
        
    }//GEN-LAST:event_eventActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Logged out");
        this.dispose();
        new entry().setVisible(true);
        
  
    }//GEN-LAST:event_logoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usermain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton cinema;
    javax.swing.JButton event;
    javax.swing.JLabel jLabel1;
    javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

}
